### ISSUE TITLE
[ERROR] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() 

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube-Encoder#144]
**From encoder logs:**

```
PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/objects/functions.php:60
Stack trace:
#0 /var/www/html/objects/Encoder.php(886): url_get_contents('/var/www/html/v...')
#1 /var/www/html/view/status.php(34): Encoder::getVideoConversionStatus('13')
#2 {main}
  thrown in /var/www/html/objects/functions.php on line 60
```
**From Chrome console I see:**

```
GET http://encoder.watchtoday.tv/status 500 (Internal Server Error)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:332
setTimeout (async)
success @ ?justLogin=1:331
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
checkProgress @ ?justLogin=1:275
(anonymous) @ ?justLogin=1:375
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
ready @ jquery-3.2.0.min.js:2
S @ jquery-3.2.0.min.js:3
```
**No error of note from webserver (YouPHPTube install)

End result is progress bar never updates until I manually refresh page.**
![image](https://user-images.githubusercontent.com/50684644/58209115-44f20e80-7c9b-11e9-8317-65818e6db153.png)

**Comment by bloomberg21** [comment]
**Fixed!**

If anybody runs into this run from cmd line:

`sudo apt-get install php7.1-mbstring php7.1-mcrypt 7.1-mysql 7.1-xml`


It seems like the build was missing XML fort some odd reason
