### ISSUE TITLE
Public encoder fails to transmit some videos

### ISSUE THREAD

**Issue by jorgeiglesiasca** [YouPHPTube/YouPHPTube-Encoder#173]
I´m doing my own research to find out why it happens.  It does not appears to follow a pattern.  Some videos upload and some not  , the ones wich get stuck wont be deleted from the upload list in the enconder. Once the encoder has finished video thumbnail is created but no video appears on web. 

Size limit and upload limit in php is set to 6gb , videos  are all mp4 , some of them are 350mb and fail so i think is not a size problem.

https://www.promocion78.com

**Comment by DanielnetoDotCom** [comment]
an important information what is the final file size after encode the video? it may be bigger then the original file

check your streamer and encoder log to try to find some clue

what is your streamer max filesize?

**Comment by jorgeiglesiasca** [comment]
I Have this values in my php ini 

Server have 8GB Ram Quad Xeon and 200GB ssd so i guess is enought to handle it.

memory_limit 6G
max_execution_time 120
max_input_time 120
post_max_size 6G
upload_max_filesize 6G

I cant read the log of the encoder because is the public one so i dont have access to FTP to check the log files in the encoder.

**Comment by DanielnetoDotCom** [comment]
what about your streamer log?

**Comment by jorgeiglesiasca** [comment]
This is the last part of the log

Stack trace:
#0 /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[19-Sep-2019 12:57:34 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d837228d8c0e9.09979124 
[19-Sep-2019 12:57:34 UTC] getVideosURL age: 563 minimumExpirationTime: 31536000
[19-Sep-2019 12:57:34 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8143f36a1395.66409874 
[19-Sep-2019 12:57:34 UTC] getVideosURL age: 144273 minimumExpirationTime: 31536000
[19-Sep-2019 12:57:34 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d814002e8f808.33572867 
[19-Sep-2019 12:57:34 UTC] getVideosURL age: 144345 minimumExpirationTime: 31536000
[19-Sep-2019 12:57:34 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/videos/cache/fonts/glyphicons-halflings-regular.woff/" in /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[19-Sep-2019 12:57:34 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/videos/cache/fonts/glyphicons-halflings-regular.ttf/" in /var/www/vhosts/volarenasturias.com/javierblanco.volarenasturias.com/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300

**Comment by DanielnetoDotCom** [comment]
ok, clearly you have a fatal error

PHP Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found

did you enable the mod_rewrite?

I am not sure why are you rising this error

**Comment by jorgeiglesiasca** [comment]
I have reinstalled just to check , it looks something was wrong in some file because it´s working now

**Comment by jorgeiglesiasca** [comment]
I post here a new log, the problem still happening even if no error is found on log now.   Can you please check encoder log to see wich can be the problem?   My log paste is here

[22-Sep-2019 14:24:37 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d86207c46f001.84768381 
[22-Sep-2019 14:24:37 UTC] getVideosURL age: 70442 minimumExpirationTime: 31536000
[22-Sep-2019 14:24:37 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:24:37 UTC] getVideosURL age: 15233 minimumExpirationTime: 31536000
[22-Sep-2019 14:24:37 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:24:37 UTC] getVideosURL age: 15233 minimumExpirationTime: 31536000
[22-Sep-2019 14:24:37 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:24:37 UTC] getVideosURL age: 15233 minimumExpirationTime: 31536000
[22-Sep-2019 14:26:32 UTC] Start Login Request
[22-Sep-2019 14:26:32 UTC] redirectUri: https://promocion78.com/mvideos
[22-Sep-2019 14:26:32 UTC] sane redirectUri: https://promocion78.com/mvideos
[22-Sep-2019 14:26:32 UTC] user::login: noPass = , encodedPass = , this->user, admin 83.45.165.78
[22-Sep-2019 14:26:32 UTC] encryptPasswordVerify: encrypt
[22-Sep-2019 14:26:32 UTC] user::login: Do login without cookie
[22-Sep-2019 14:26:32 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:26:32 UTC] getVideosURL age: 15348 minimumExpirationTime: 31536000
[22-Sep-2019 14:26:32 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8743db51d333.13546961 
[22-Sep-2019 14:26:32 UTC] getVideosURL age: 9421 minimumExpirationTime: 31536000
[22-Sep-2019 14:26:32 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8741fecefde8.96936019 
[22-Sep-2019 14:26:32 UTC] getVideosURL age: 9420 minimumExpirationTime: 31536000
[22-Sep-2019 14:26:32 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d86207c46f001.84768381 
[22-Sep-2019 14:26:32 UTC] getVideosURL age: 70557 minimumExpirationTime: 31536000
[22-Sep-2019 14:26:32 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d83fce35e5404.01459774 
[22-Sep-2019 14:26:32 UTC] getVideosURL age: 228712 minimumExpirationTime: 31536000
[22-Sep-2019 14:26:57 UTC] Start Login Request
[22-Sep-2019 14:26:57 UTC] redirectUri: 
[22-Sep-2019 14:26:57 UTC] sane redirectUri: https://promocion78.com/
[22-Sep-2019 14:26:57 UTC] user::login: noPass = , encodedPass = true, this->user, admin 192.99.14.108
[22-Sep-2019 14:26:57 UTC] encryptPasswordVerify: do not encrypt
[22-Sep-2019 14:26:57 UTC] user::login: Do login without cookie
[22-Sep-2019 14:27:07 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d86207c46f001.84768381 
[22-Sep-2019 14:27:07 UTC] getVideosURL age: 70592 minimumExpirationTime: 31536000
[22-Sep-2019 14:27:07 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:27:07 UTC] getVideosURL age: 15383 minimumExpirationTime: 31536000
[22-Sep-2019 14:27:07 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:27:07 UTC] getVideosURL age: 15383 minimumExpirationTime: 31536000
[22-Sep-2019 14:27:07 UTC] getVideosURL Cache in 0.0005 seconds. fileName: _YPTuniqid_5d8744bd248924.19904657 
[22-Sep-2019 14:27:07 UTC] getVideosURL age: 15383 minimumExpirationTime: 31536000

**Comment by DanielnetoDotCom** [comment]
there is no error in this new log

can you reproduce the error using public encoder and demo site?

what exactly video are you using to encode?

**Comment by jorgeiglesiasca** [comment]
The problem is not on demo site , is between my server (plesk) and public encoder.

I´ve just uploaded some new videos ,  the next title is having same problem so you can check

Promocion 2009_converted(1)_converted

**Comment by jorgeiglesiasca** [comment]
ok , it seems that php options are limited in plesk for one file, adding to extra parameters the next :

LimitRequestBody 2147483647 

Seems to fix the problem.  Will tell you later

**Comment by jorgeiglesiasca** [comment]
Ok , now works but no HD video is shown , looks like it does 3 passes in public encoder but after only sd video on web

**Comment by jorgeiglesiasca** [comment]
i´m getting mad with this stuff , looks like plesk or something is blocking bigger files than ... X  and anithing wich after encoding is lower than that size is uploading well and the rest are missing , no idea where it fails , php ini is correct and encoder shows 6gb limit on my server so it reads it well.  
Any ideaS?

**Comment by DanielnetoDotCom** [comment]
Hi, make sure you are aware of it https://github.com/YouPHPTube/YouPHPTube/wiki/About-Video-Upload#cloudflare

**Comment by jorgeiglesiasca** [comment]
Yes , i was aware because while trying to find what is happening ivé read almost every closed issue here related to failures between encoder and streamer , but i´m not using cloudflare so it cant be in that direction the problem. 

I have a plesk onix  Virtual Server on server4you , all php.ini related to the domain are around 6gb and timeouts are in 3600 so the only thing i can think is virtuozzo have any kind of filesize limitation for its containers but in server4you they told me that they are not blocking any kind of data transfer of any size.   I´m completely lost after a week with this issue

**Comment by DanielnetoDotCom** [comment]
I am also lost, If the problem is not the file size you may find something in your log file.

**Comment by jorgeiglesiasca** [comment]
I think i found the problem.  Plesk have a Nginx reverse proxy with apache. Reverse proxy have a max body limit of 128 wich is not configurable from panel.  With console commands we can change the value.  Now i´m uploading a big file to test, will tell later.  Just in case  someone have this issue in a plesk server i leave here the link with how to change  client_max_body because from panel parameters it fails to apply.

https://support.plesk.com/hc/en-us/articles/213914565-Invalid-nginx-configuration-nginx-emerg-client-max-body-size-directive-is-duplicate

**Comment by DanielnetoDotCom** [comment]
thanks for sharing this

**Comment by jorgeiglesiasca** [comment]
Fixed .  Just finished uploading a video of 700mb with no problem HD SD and LOW appears for first time.  

Closing issue finally, thanks for your help!!
